version: '3'

networks:
  app-tier:
    driver: bridge

services:
  appProducer:
    image: 'docker-spring-boot:latest'
    networks:
      - app-tier
    ports:
      - "7072:7072"
    build:
      context: .
    container_name: kafka-producer

  kafka-1:
    image: bitnami/kafka:latest
    networks:
      - app-tier
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_KRAFT_CLUSTER_ID=p_18axXbTnOFRzwVmNngXg
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka-1:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_DAEMON_GROUP=group
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_HOSTNAME=docker.for.mac.localhost

    volumes:
        - /Users/alina/homeKafkaLC/tmp/server-credit/:/bitnami/kafka